import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.argv[2];
if (!root) throw new Error("Usage: node scripts/snapshot-sources.mjs /path/to/agentic-rl-analysis");
const revision = "66ae4423b36270ef50a288fb1bb2e1b31c46c329";
const head = execFileSync("git", ["-C", root, "rev-parse", "HEAD"], { encoding: "utf8" }).trim();
if (head !== revision) throw new Error(`Expected frozen upstream ${revision}; got ${head}`);
const paths = execFileSync("git", ["-C", root, "ls-tree", "-r", "--name-only", revision], { encoding: "utf8" })
  .trim().split("\n").filter(path => /\.mdx?$/.test(path)).sort();
if (paths.length !== 37) throw new Error(`Expected 37 source documents; got ${paths.length}`);
const documents = paths.map(path => {
  const content = execFileSync("git", ["-C", root, "show", `${revision}:${path}`]);
  const local = readFileSync(resolve(root, path));
  if (!content.equals(local)) throw new Error(`Upstream working copy differs: ${path}`);
  return {
    path,
    sha256: createHash("sha256").update(content).digest("hex"),
    bytes: content.length,
    headings: content.toString("utf8").split("\n").filter(line => /^#{1,6} /.test(line)),
  };
});
const output = new URL("../docs/research/source-inventory.json", import.meta.url);
mkdirSync(new URL("../docs/research/", import.meta.url), { recursive: true });
writeFileSync(output, JSON.stringify({ repository: "https://github.com/XavierZhang2002/agentic-rl-analysis", revision, documents }, null, 2) + "\n");
writeFileSync(new URL("../content/source-revision.js", import.meta.url),
  "// Generated by scripts/snapshot-sources.mjs from the frozen upstream commit.\n" +
  `export const SOURCE_REVISION = ${JSON.stringify(revision)};\n` +
  `export const SOURCE_FILES = Object.freeze(${JSON.stringify(documents.map(({ path, sha256 }) => ({ path, sha256 })), null, 2)});\n`);
console.log(`${documents.length} document hashes and heading inventories saved`);
